<?php include("AdminNavBar.php"); 
$result = $_GET['createHospitalOfficial'];
include_once("admincreateHospitalOfficial.php");       //COULD BE ISSUE WITH THIS CHANGED THE NAME OF THE FILE FROM STAFFCREATEUSERSQL TO THIS
?>

<div class="container">
    <main role="main" class="pb-3"> 
        <section class="home" id="home">
            <div class="content">
        <h3>Hospital Official Creation Result</h3>
        <h2><div>
            <?php
                if($result){
                echo "Here is the Hospital Official autogenerated ID and Password - make sure to note this down as you will need this to login to your account to access our facilities. Your Hospital Official ID is : " . $_SESSION['HOOA_ID'] . " and your Password is: " . $_SESSION['HOOA_Password'];
    
                }
                else{
                    echo "Error";
                }
            ?>
            <div><a href="AddHospitalOfficial.php">Back</a></div>
        </div></h2>
    </div>
</section>
        </main>
    </div>