<?php include("receptionistNavBar.php"); 
$result = $_GET['createpatient'];
include_once("receptionistcreatePateint.php");       //COULD BE ISSUE WITH THIS CHANGED THE NAME OF THE FILE FROM STAFFCREATEUSERSQL TO THIS
?>

<div class="container">
    <main role="main" class="pb-3"> 
        <section class="home" id="home">
            <div class="content">
        <h3>Patient Creation Result</h3>
        <h2><div>
            <?php
                if($result){
                echo "Here is the Patient's autogenerated ID and Password - make sure to note this down as you will need this to login to your account to access our facilities. Your Patient ID is : " . $_SESSION['Patient_ID'] . " and your Password is: " . $_SESSION['Patient_Password'];
    
                }
                else{
                    echo "Error";
                }
            ?>
            <div><a href="AddPatient.php">Back</a></div>
        </div></h2>
    </div>
</section>
        </main>
    </div>
